import 'achievement_definition.dart';

/// List of all possible achievements in the app
final List<AchievementDefinition> achievementDefinitions = [
  // Time achievements
  AchievementDefinition(
    id: 'time_first_day',
    name: 'First Day',
    description: 'Complete 24 hours without smoking',
    category: 'TIME',
    requirementType: 'DAYS_SMOKE_FREE',
    requirementValue: 1,
    badgeText: '24h',
    iconName: 'calendar_today',
    orderIndex: 1,
    xpReward: 10,
  ),
  AchievementDefinition(
    id: 'time_one_week',
    name: 'One Week',
    description: 'One week without smoking!',
    category: 'TIME',
    requirementType: 'DAYS_SMOKE_FREE',
    requirementValue: 7,
    badgeText: '7 days',
    iconName: 'celebration',
    orderIndex: 2,
    xpReward: 25,
  ),
  AchievementDefinition(
    id: 'time_two_weeks',
    name: 'Two Weeks',
    description: 'Two complete weeks without smoking!',
    category: 'TIME',
    requirementType: 'DAYS_SMOKE_FREE',
    requirementValue: 14,
    badgeText: '14 days',
    iconName: 'calendar_month',
    orderIndex: 3,
    xpReward: 50,
  ),
  AchievementDefinition(
    id: 'time_one_month',
    name: 'One Month',
    description: 'A whole month without smoking!',
    category: 'TIME',
    requirementType: 'DAYS_SMOKE_FREE',
    requirementValue: 30,
    badgeText: '30 days',
    iconName: 'emoji_events',
    orderIndex: 4,
    xpReward: 100,
  ),
  AchievementDefinition(
    id: 'time_three_months',
    name: 'Three Months',
    description: 'Three months smoke-free!',
    category: 'TIME',
    requirementType: 'DAYS_SMOKE_FREE',
    requirementValue: 90,
    badgeText: '90 days',
    iconName: 'military_tech',
    orderIndex: 5,
    xpReward: 250,
  ),
  AchievementDefinition(
    id: 'time_six_months',
    name: 'Six Months',
    description: 'Half a year without smoking!',
    category: 'TIME',
    requirementType: 'DAYS_SMOKE_FREE',
    requirementValue: 180,
    badgeText: '180 days',
    iconName: 'workspace_premium',
    orderIndex: 6,
    xpReward: 500,
  ),
  AchievementDefinition(
    id: 'time_one_year',
    name: 'One Year',
    description: 'One year smoke-free anniversary!',
    category: 'TIME',
    requirementType: 'DAYS_SMOKE_FREE',
    requirementValue: 365,
    badgeText: '1 year',
    iconName: 'verified',
    orderIndex: 7,
    xpReward: 1000,
  ),
  
  // Health achievements (aligned with Health Recovery system)
  
  // Blood Oxygen Normalization - Day 1
  AchievementDefinition(
    id: 'health_blood_oxygen',
    name: 'Blood Oxygen Normalization',
    description: 'Your blood oxygen levels have returned to normal',
    category: 'HEALTH',
    requirementType: 'HEALTH_RECOVERY',
    requirementValue: '67e41169-fb32-4617-b153-3356ce7f19af', // Actual UUID from health_recoveries table
    badgeText: 'O2 Levels',
    iconName: 'bloodtype',
    orderIndex: 1,
    xpReward: 20,
  ),
  
  // Carbon Monoxide Eliminated - Day 2
  AchievementDefinition(
    id: 'health_carbon_monoxide',
    name: 'Carbon Monoxide Eliminated',
    description: 'Carbon monoxide has been eliminated from your body',
    category: 'HEALTH',
    requirementType: 'HEALTH_RECOVERY',
    requirementValue: '45772711-7a62-4aa2-9181-dabd51bb90e9', // Actual UUID from health_recoveries table
    badgeText: 'CO Free',
    iconName: 'air_purifier_gen',
    orderIndex: 2,
    xpReward: 20,
  ),
  
  // Improved Taste - Day 3
  AchievementDefinition(
    id: 'health_taste',
    name: 'Improved Taste',
    description: 'Your sense of taste has begun to improve',
    category: 'HEALTH',
    requirementType: 'HEALTH_RECOVERY',
    requirementValue: 'd58be1e0-0be8-4565-9c36-f52d3431cd01', // Actual UUID from health_recoveries table
    badgeText: 'Taste',
    iconName: 'restaurant',
    orderIndex: 3,
    xpReward: 20,
  ),
  
  // Improved Smell - Day 3
  AchievementDefinition(
    id: 'health_smell',
    name: 'Improved Smell',
    description: 'Your sense of smell has begun to improve',
    category: 'HEALTH',
    requirementType: 'HEALTH_RECOVERY',
    requirementValue: '704cd551-244f-4a09-83b1-c45ce3563f76', // Actual UUID from health_recoveries table
    badgeText: 'Smell',
    iconName: 'air',
    orderIndex: 4,
    xpReward: 20,
  ),
  
  // Nicotine Expulsion - Day 4
  AchievementDefinition(
    id: 'health_nicotine',
    name: 'Nicotine Expulsion',
    description: 'Nicotine has been completely expelled from your body',
    category: 'HEALTH',
    requirementType: 'HEALTH_RECOVERY',
    requirementValue: '6e0b16cb-aa5b-4cbc-ab66-ad1a0b3f8e12', // Actual UUID from health_recoveries table
    badgeText: 'Nicotine Free',
    iconName: 'science',
    orderIndex: 5,
    xpReward: 20,
  ),
  
  // Improved Breathing - Day 7
  AchievementDefinition(
    id: 'health_breathing',
    name: 'Improved Breathing',
    description: 'Your lung function has started to improve',
    category: 'HEALTH',
    requirementType: 'HEALTH_RECOVERY',
    requirementValue: '54040fef-cbf4-4d4a-a7c4-c4d7c881bea3', // Actual UUID from health_recoveries table
    badgeText: 'Breathing',
    iconName: 'air_sharp',
    orderIndex: 6,
    xpReward: 30,
  ),
  
  // Improved Circulation - Day 14
  AchievementDefinition(
    id: 'health_circulation',
    name: 'Improved Circulation',
    description: 'Your circulation has begun to improve',
    category: 'HEALTH',
    requirementType: 'HEALTH_RECOVERY',
    requirementValue: '2e5b6a11-4bc9-4cff-89d6-9b8ee7b1b246', // Actual UUID from health_recoveries table
    badgeText: 'Circulation',
    iconName: 'favorite',
    orderIndex: 7,
    xpReward: 50,
  ),
  
  // Decreased Coughing - Day 30
  AchievementDefinition(
    id: 'health_coughing',
    name: 'Decreased Coughing',
    description: 'Coughing and shortness of breath decrease',
    category: 'HEALTH',
    requirementType: 'HEALTH_RECOVERY',
    requirementValue: '13a9cb3f-f28c-40f9-8384-458e2c70daf3', // Actual UUID from health_recoveries table
    badgeText: 'Clear Lungs',
    iconName: 'healing',
    orderIndex: 8,
    xpReward: 50,
  ),
  
  // Lung Cilia Recovery - Day 90
  AchievementDefinition(
    id: 'health_lung_cilia',
    name: 'Lung Cilia Recovery',
    description: 'Lung cilia regrow, increasing ability to handle mucus',
    category: 'HEALTH',
    requirementType: 'HEALTH_RECOVERY',
    requirementValue: '69879743-94e7-4cb2-b398-5df99e67e78f', // Actual UUID from health_recoveries table
    badgeText: 'Lung Repair',
    iconName: 'air_rounded',
    orderIndex: 9,
    xpReward: 100,
  ),
  
  // Reduced Heart Disease Risk - Day 365
  AchievementDefinition(
    id: 'health_heart',
    name: 'Reduced Heart Disease Risk',
    description: 'Your risk of coronary heart disease has decreased to half',
    category: 'HEALTH',
    requirementType: 'HEALTH_RECOVERY',
    requirementValue: 'efaaf246-f824-4ae3-9ab0-4916e134c773', // Actual UUID from health_recoveries table
    badgeText: 'Heart Health',
    iconName: 'favorite_border',
    orderIndex: 10,
    xpReward: 300,
  ),
  
  // Savings achievements
  AchievementDefinition(
    id: 'savings_first_pack',
    name: 'Initial Savings',
    description: 'Save the equivalent of 1 pack of cigarettes',
    category: 'SAVINGS',
    requirementType: 'MONEY_SAVED',
    requirementValue: 1,
    badgeText: 'First Pack',
    iconName: 'savings',
    orderIndex: 1,
    xpReward: 15,
  ),
  AchievementDefinition(
    id: 'savings_five_packs',
    name: 'Smart Saver',
    description: 'Save the equivalent of 5 packs',
    category: 'SAVINGS',
    requirementType: 'MONEY_SAVED',
    requirementValue: 5,
    badgeText: '5 Packs',
    iconName: 'attach_money',
    orderIndex: 2,
    xpReward: 30,
  ),
  AchievementDefinition(
    id: 'savings_ten_packs',
    name: 'Substantial Savings',
    description: 'Save the equivalent of 10 packs',
    category: 'SAVINGS',
    requirementType: 'MONEY_SAVED',
    requirementValue: 10,
    badgeText: '10 Packs',
    iconName: 'monetization_on',
    orderIndex: 3,
    xpReward: 60,
  ),
  AchievementDefinition(
    id: 'savings_twenty_five_packs',
    name: 'Money Milestone',
    description: 'Save the equivalent of 25 packs',
    category: 'SAVINGS',
    requirementType: 'MONEY_SAVED',
    requirementValue: 25,
    badgeText: '25 Packs',
    iconName: 'savings_outlined',
    orderIndex: 4,
    xpReward: 125,
  ),
  AchievementDefinition(
    id: 'savings_hundred_packs',
    name: 'Financial Freedom',
    description: 'Save the equivalent of 100 packs',
    category: 'SAVINGS',
    requirementType: 'MONEY_SAVED',
    requirementValue: 100,
    badgeText: '100 Packs',
    iconName: 'account_balance',
    orderIndex: 5,
    xpReward: 500,
  ),
  
  // Habits achievements
  AchievementDefinition(
    id: 'habits_streak_starter',
    name: 'Streak Starter',
    description: 'Record activity for 3 consecutive days',
    category: 'HABITS',
    requirementType: 'LOGIN_STREAK',
    requirementValue: 3,
    badgeText: 'Streak',
    iconName: 'trending_up',
    orderIndex: 1,
    xpReward: 10,
  ),
  AchievementDefinition(
    id: 'habits_consistency',
    name: 'Consistency Champion',
    description: 'Record activity for 7 consecutive days',
    category: 'HABITS',
    requirementType: 'LOGIN_STREAK',
    requirementValue: 7,
    badgeText: 'Consistent',
    iconName: 'auto_graph',
    orderIndex: 2,
    xpReward: 25,
  ),
  AchievementDefinition(
    id: 'habits_formed',
    name: 'Habit Formed',
    description: 'Record activity for 21 consecutive days',
    category: 'HABITS',
    requirementType: 'LOGIN_STREAK',
    requirementValue: 21,
    badgeText: 'Habit',
    iconName: 'published_with_changes',
    orderIndex: 3,
    xpReward: 75,
  ),
  AchievementDefinition(
    id: 'habits_resisted_ten',
    name: 'Resisted Cravings',
    description: 'Successfully resist 10 cravings',
    category: 'HABITS',
    requirementType: 'CRAVINGS_RESISTED',
    requirementValue: 10,
    badgeText: 'Willpower',
    iconName: 'fitness_center',
    orderIndex: 4,
    xpReward: 50,
  ),
  AchievementDefinition(
    id: 'habits_resisted_fifty',
    name: 'Craving Crusher',
    description: 'Successfully resist 50 cravings',
    category: 'HABITS',
    requirementType: 'CRAVINGS_RESISTED',
    requirementValue: 50,
    badgeText: 'Crusher',
    iconName: 'psychology',
    orderIndex: 5,
    xpReward: 200,
  ),
  AchievementDefinition(
    id: 'habits_exercise',
    name: 'New Habit: Exercise',
    description: 'Record 5 days of exercise',
    category: 'HABITS',
    requirementType: 'EXERCISE_LOGGED',
    requirementValue: 5,
    badgeText: 'Active',
    iconName: 'directions_run',
    orderIndex: 6,
    xpReward: 35,
  ),
];